# This is here only so the Ingress example has both backends.
# If you've already created frontend-service elsewhere, skip applying this file.
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
  type: NodePort