apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-frontend
  labels:
    app: devops-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-frontend
  template:
    metadata:
      labels:
        app: devops-frontend
    spec:
      containers:
      - name: devops-frontend
        image: 931936006344.dkr.ecr.ap-south-1.amazonaws.com/devopsbox-frontend:latest   # React + Vite frontend
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: devops-frontend-service
spec:
  selector:
    app: devops-frontend
  ports:
  - protocol: TCP
    port: 80        # Service port
    targetPort: 80  # Container port
  type: NodePort
