apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-frontend
  labels:
    app: devops-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-frontend
  template:
    metadata:
      labels:
        app: devops-frontend
    spec:
      containers:
      - name: devops-frontend
        image: devopsfrontend:midsemv2 # Replace with your registry if you push it (e.g., dockerhub/ghcr)
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: devops-frontend-service
spec:
  selector:
    app: devops-frontend
  ports:
  - protocol: TCP
    port: 80        # Service port
    targetPort: 3000 # Container port
  type: NodePort    # Change to LoadBalancer if using cloud (EKS/GKE/AKS)
