apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devopsbox-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "false" 
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: devops-backend-service
                port:
                  number: 5000

         
          - path: /
            pathType: Prefix
            backend:
              service:
                name: devops-frontend-service
                port:
                  number: 80

