apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devopsbox-ingress
spec:
  rules:
  - host: devopsbox.local
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: backend-service
            port:
              number: 5000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: devops-frontend-service
            port:
              number: 80
