apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: default-serviceaccount-admin
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin # Binds the default ServiceAccount to the cluster-admin role
  apiGroup: rbac.authorization.k8s.io
